openapi: 3.1.0
info:
  version: v1
  title: content-vault API
  description: content-vault RESTFul api for openapi 3.1
  termsOfService: 'https://jumkid.com/terms-of-use'
  contact:
    name: Chooli Yip
    url: jumkid.com
    email: chooli.yip@gmail.com
  license:
    name: Jumkid Public License
    url: 'http://license.jumkid.com'
servers:
  - description: Testing
    url: 'http://test.jumkid.com'
  - description: Live production
    url: 'http://api.jumkid.com'
tags:
  - name: v1
    description: API for version 1.0.2
  - name: test
    description: API for test
security:
  - bearerAuth: []
paths:
  /metadata:
    get:
      tags:
        - v1
      operationId: searchMetadata
      description: search metadata with query and size
      parameters:
        - name: q
          in: query
          required: false
          description: query string
          schema:
            type: string
        - name: size
          in: query
          required: false
          description: size of result set
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaFile'
    post:
      tags:
        - v1
      operationId: addMetadata
      description: save a new metadata
      parameters:
        - name: mediaFileModule
          in: query
          required: true
          description: mediaFile module
          schema:
            $ref: '#/components/schemas/MediaFileModule'
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaFile'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'
      summary: Add raw metadata
  '/metadata/{id}':
    get:
      tags:
        - v1
      operationId: getMetadata
      description: get single metadata for media file
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'
    put:
      tags:
        - v1
      operationId: updateMetadata
      description: update metadata for media file
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
      requestBody:
        description: partial metadata json object
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaFile'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'

    delete:
      tags:
        - v1
      operationId: deleteMetadata
      description: delete single metadata for media file
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
            
      responses:
        '204':
          description: successfully delete the metadata by givn id
          content:
            application/json:
              schema:
                type: integer

  '/content/{id}':
    get:
      tags:
        - v1
      operationId: getPlain
      description: get plain content
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
        - name: ignoreTitle
          in: query
          required: false
          description: if the response body should ignore the title
          schema:
            type: boolean
      responses:
        '200':
          description: successfully fetch content in plain format
          content:
            test/plain:
              schema:
                type: string

  /content:
    post:
      tags:
        - v1
      operationId: addTextContent
      description: save a new plain content
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
        - name: content
          in: query
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'
      summary: Add text content

  /content/html:
    post:
      tags:
        - v1
      operationId: addHtmlContent
      description: save a new text content
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
      requestBody:
        content:
          application/json:
            schema:
              type: object
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'
      summary: Add html content

  '/content/stream/{id}':
    get:
      tags:
        - v1
      operationId: stream
      description: stream content
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
        - name: size
          in: query
          description: size option
          schema:
            $ref: '#/components/schemas/ThumbnailSize'
      responses:
        '200':
          description: binary stream as response
  '/content/thumbnail/{id}':
    get:
      tags:
        - v1
      operationId: thumbnail
      description: get thumbnail image by given content id
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
      responses:
        '200':
          description: binary as response

## Gallery API
  /gallery:
    post:
      tags:
        - v1
      operationId: saveGallery
      description: save multiple file as gallery
      parameters:
        - name: title
          in: query
          required: true
          schema:
            type: string
        - name: content
          in: query
          required: false
          schema:
            type: string
        - name: files
          in: query
          required: false
          schema:
            type: array
            format: file
        - name: tags
          in: query
          required: false
          schema:
            type: array
            format: string
            
      responses:
        '202':
          description: save a gallery with multiple files upload
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'

  '/gallery/{id}':
    post:
      tags:
        - v1
      operationId: updateItems
      description: update a gallery with file upload
      parameters:
        - name: id
          in: path
          required: true
          description: gallery identifier
          schema:
            type: string
        - name: featuredId
          in: query
          required: false
          description: representative image of the gallery
          schema:
            type: string
        - name: files
          in: query
          required: false
          schema:
            type: array
            format: file

      responses:
        '202':
          description: updated a gallery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'

    put:
      tags:
        - v1
      operationId: update
      description: update a gallery with partialMediaFile or child media file list
      parameters:
        - name: id
          in: path
          required: true
          description: gallery identifier
          schema:
            type: string

      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/MediaFile'

      responses:
        '202':
          description: updated a gallery
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'

  /file/upload:
    post:
      tags:
        - v1
      operationId: upload
      description: file upload
      parameters:
        - name: title
          in: query
          required: false
          description: title of file
          schema:
            type: string
        - name: content
          in: query
          required: false
          description: content of file
          schema:
            type: string
        - name: tags
          in: query
          required: false
          description: tags of file
          schema:
            type: array  
            format: string   

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                file:
                  type: string
                  format: binary
                tags:
                  type: array
                  format: string
                  
      responses:
        '202':
          description: upload a new content in file format
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/MediaFile'

  /file/multipleUpload:
    post:
      tags:
        - v1
      operationId: multipleUpload
      description: multiple files upload
      parameters:
        - name: tags
          in: query
          required: false
          description: tags of files
          schema:
            type: array
            format: string

      requestBody:
        content:
          multipart/form-data:
            schema:
              type: object
              properties:
                files:
                  type: array
                  format: binary
                tags:
                  type: array
                  format: string

      responses:
        '202':
          description: upload multiple content in file format
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaFile'

  '/file/download/{id}':
    get:
      tags:
        - v1
      operationId: download
      description: download file with the identifier
      parameters:
        - name: id
          in: path
          required: true
          description: mediafile identifier
          schema:
            type: string
      responses:
        '200':
          description: binary file as response
  /ingest/webpage:
    post:
      tags:
        - v1
      operationId: convertUrlToMediafile
      description: capture a screenshort from the given url
      parameters:
        - name: url
          in: query
          required: true
          description: target url
          schema:
            type: string
        - name: title
          in: query
          required: true
          description: target title
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaFile'
  /trash:
    get:
      tags:
        - v1
      operationId: getAllTrash
      description: fetch all deleted files in the trash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/MediaFile'
                  
    delete:
      tags:
        - v1
      operationId: emptyTrash
      description: delete all files in the trash
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: number

components:
  schemas:
    MediaFile:
      description: Model of media file
      properties:
        id:
          type: string
          example: 1mWG-nQBWmmN0po1BUoG
        filename:
          type: string
          example: foo.txt
        mimeType:
          type: string
          example: text/plain
        size:
          type: integer
          description: file size in byte
        title:
          type: string
        content:
          type: string
        activated:
          type: boolean
        createdBy:
          type: string
        creationDate:
          $ref: https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/LocalDateTime
        modifiedBy:
          type: string
        modificationDate:
          $ref: https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/LocalDateTime
        props:
          type: array
          items:
            description: list of additional properties
            properties:
              name:
                type: string
              textValue:
                type: string
              dateValue:
                $ref: https://raw.githubusercontent.com/jumkid/share-jar/master/src/main/resources/share.yaml#/components/schemas/LocalDateTime
              numberValue:
                type: integer
        tags:
          type: array
          items:
            description: list of tags
            type: string
        children:
          type: array
          items:
            $ref: '#/components/schemas/MediaFile'
    
    MediaFileField:
      type: string
      enum:
        - title
        - filename
        - mimeType
        - module
        - content

    MediaFileModule:
      type: string
      enum:
        - FILE
        - TEXT
        - HTML
        - GALLERY
    
    ThumbnailSize:
      type: string
      enum:
        - small
        - large
  
  securitySchemes:
    bearerAuth:
      type: http
      scheme: bearer
      bearerFormat: JWT
